# Whether the whole plugin should be enabled
enabled: true

# The default language to use when no language file exists for the client's language
default-lang: en

# How much collected experience is required to repair one durability point.
# MendingNerf adds additional required exp based on an item's repair cost
# Vanilla base value is 0.5
base-exp-for-repair: 0.5

# The maximum that the repair cost can grow to. After that the item can't be repaired
max-repair-cost: 100

# Whether mending should be nerfed. If disabled then only anvil repairs will be blocked above the max cost.
mending-nerf: true

# The plugin uses the maximum durability of the item which is mended as the basis for the calculation
# when the repair cost should increase. So a increase-cost-step-modifier of 1 for a diamond pickaxe means
# that it will increase the cost each 1561s repairs. 0.5 each ~780th etc.
increase-cost-step-modifier: 1.0

# By how much the required exp for mending one durability should be increased per repair-cost on the item
# Basically "required exp for 1 repair" = (base-exp-for-repair) + (item repair-cost) * (repair-cost-modifier)
repair-cost-modifier: 2